repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        additional_dependencies: ["click<8.1.0"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.2.5
    hooks:
      - id: prettier
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.3
    hooks:
      - id: gitleaks



